/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graduate.student_view;

import graduate.login.login_log;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rlarl
 */
public class student_Setclass extends javax.swing.JFrame {

    /**
     * Creates new form student_Setclass
     */
    public student_Setclass() {
        initComponents();
        login_log a = new login_log();
        a.Read_log();
        String Class = a.login_log[4];
        jLabel10.setText(Class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("신청 가능 학점 : ");

        jLabel2.setText("학점");

        jLabel4.setText("현재 신청 학점 : ");

        jLabel5.setText("학점");

        jButton1.setText("담  기");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("확  인");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel7.setText("신청 강좌");

        jLabel8.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jLabel8.setText("개설 강좌");

        jLabel9.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel9.setText("수강신청");

        jLabel10.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("18");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("0");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2019", "2018", "2017" }));

        jLabel3.setText("년도");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 학기", "2 학기" }));

        jButton3.setText("이  전");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("시  작");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("빼  기");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(249, 249, 249))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton5.setEnabled(true);
        login_log a = new login_log();
        a.Read_log();
        String stra = a.login_log[1];
        String Class = a.login_log[4];
        String Year = jComboBox1.getSelectedItem().toString();
        String Semester = jComboBox2.getSelectedItem().toString();

         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        DefaultTableModel modeln = (DefaultTableModel)jTable2.getModel();
        String ob = "강좌번호;강좌이름;학점수;담당교수;수강가능인원;강좌설명;";
         
         for(int m=0;m<6;m++)
            { 
                String[] str = ob.split(";");
               model.setColumnIdentifiers(str);
               modeln.setColumnIdentifiers(str);
                
            }
         ReadData1();
        
         try{
               File file = new File("C:\\DB\\Class\\"+Class+" "+Year+"년도 "+Semester+"\\Semester_log.txt");
                   FileReader filereader = new FileReader(file);
               try (BufferedReader bufReader = new BufferedReader(filereader)) {
                    Object[] tableLines = bufReader.lines().toArray(); 
                    for(int i=0; i< tableLines.length;i++){
                        String line=tableLines[i].toString().trim();
                            String[] dataRow = line.split("\t");
                            String strb = dataRow[0];
                            if(strb.equals(stra)){
                                JOptionPane.showMessageDialog(null, "이미 수강신청을 완료했습니다.");
                                jButton1.setEnabled(false);
                                jButton2.setEnabled(false);
                                jButton5.setEnabled(false);
                            }
                    }    
                    filereader.close();
                  bufReader.close();
               }
            }catch (FileNotFoundException e){
                System.out.println(e);
            }catch(IOException e){
                System.out.println(e);
            }
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row = jTable2.getSelectedRow(); 
        String[] a = null;
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        boolean status = true;
        int limit = 18; // 원래 20
        int num = Integer.parseInt(jLabel12.getText());
        String all = jTable2.getValueAt(row, 4).toString();
        String[] people = all.split("/");
        int posible;

        
        if(row <0){
            JOptionPane.showMessageDialog(null, "담을 강좌를 선택해주세요.");
        }
        else if(jTable1.getRowCount() == 0){
            if(people[0].equals("0")){
                JOptionPane.showMessageDialog(null, "신청가능 인원을 초과했습니다.");
            }
            else{
            model.addRow(a);
            for(int i = 0; i<jTable2.getColumnCount();i++){    
                jTable1.setValueAt(jTable2.getValueAt(row, i), jTable1.getRowCount()-1, i);
            }
            num += Integer.parseInt(jTable1.getValueAt(jTable1.getRowCount()-1, 2).toString());
            jLabel12.setText(Integer.toString(num));
            
            posible = Integer.parseInt(people[0]);
            posible--;
            people[0]=Integer.toString(posible);
            all = people[0] + "/" + people[1];
            jTable2.setValueAt(all, row, 4);
            jTable1.setValueAt(all, jTable1.getRowCount()-1, 4);
            }
        }
        else{        
                for(int j=0;j<jTable1.getRowCount();j++){
                    if(jTable2.getValueAt(row, 0).equals(jTable1.getValueAt(j, 0))){
                        JOptionPane.showMessageDialog(null, "이미 담은 강의입니다.");
                        status = false;
                        break;
                    }
                }
                if(status){
                    if(num >= limit){
                        JOptionPane.showMessageDialog(null, "신청가능 학점을 초과하셨습니다.");
                    }
                    else if(num + Integer.parseInt(jTable2.getValueAt(row, 2).toString()) >limit){
                        JOptionPane.showMessageDialog(null, "신청가능 학점을 초과합니다.");
                    }
                    else if(people[0].equals("0")){
                        JOptionPane.showMessageDialog(null, "신청가능 인원을 초과했습니다.");
                    }
                    else{
                        model.addRow(a);
                        for(int i = 0; i<jTable2.getColumnCount();i++){    
                            jTable1.setValueAt(jTable2.getValueAt(row, i), jTable1.getRowCount()-1, i);
                        }
                        num += Integer.parseInt(jTable1.getValueAt(jTable1.getRowCount()-1, 2).toString());
                        jLabel12.setText(Integer.toString(num));
                        
                        posible = Integer.parseInt(people[0]);
            posible--;
            people[0]=Integer.toString(posible);
            all = people[0] + "/" + people[1];
            jTable2.setValueAt(all, row, 4);
            jTable1.setValueAt(all, jTable1.getRowCount()-1, 4);
                    }
                }
        }
         jTable2.clearSelection();
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int a = jTable1.getSelectedRow();
        String str = jTable1.getValueAt(a, 0).toString();
        int b = 0;
        for(int i=0;i<jTable2.getRowCount();i++){
                    String strn = jTable2.getValueAt(i, 0).toString();
                    if(str.equals(strn)){
                        jTable2.changeSelection(i, 1, false, false);
                        b=i;
                        break;
                    }
        
        }
        String all = jTable1.getValueAt(a, 4).toString();
        String[] people = all.split("/");
        int posible;
        int num = Integer.parseInt(jLabel12.getText());
        if(a >=0 ){
            num -= Integer.parseInt(jTable1.getValueAt(a, 2).toString());
            jLabel12.setText(Integer.toString(num));
            
            posible = Integer.parseInt(people[0]);
            posible++;
            people[0]=Integer.toString(posible);
            all = people[0] + "/" + people[1];
            jTable2.setValueAt(all, b, 4);
            
            model.removeRow(a);
        }
        else{
            JOptionPane.showMessageDialog(null, "신청강좌에서 취소할 강좌를 선택해주세요.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "신청한 강좌는 수정이 불가능 합니다.\n 신청완료 하시겠습니까?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.CLOSED_OPTION){
            
        }
	else if(result == JOptionPane.YES_OPTION){
            String year = jComboBox1.getSelectedItem().toString();
            String hacgi = jComboBox2.getSelectedItem().toString();
            login_log a = new login_log();
            a.Read_log();
            String num = a.login_log[1];
            String name = a.login_log[2];
            String Class = a.login_log[4];
            for(int i = 0; i<jTable1.getRowCount(); i++){
                String Classname = jTable1.getValueAt(i, 1).toString();
            
                try{
                File file = new File("C:\\DB\\Class\\"+Class+" "+year+"년도"+" "+hacgi+"\\"+Classname+".txt");
                if(!file.exists()){
                    file.createNewFile();
                }
                FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(num+"\t"+name+"\t"+"-");
                bw.write("\n");
                bw.close();
                fw.close(); 
          
                }catch(IOException ex){
                    System.out.println(ex);
                }
            }
            Save_Writelog();
            JOptionPane.showMessageDialog(null, "수강신청이 완료되었습니다.");
            
        }
        else{
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        student_firstview s = new student_firstview();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void ReadData1(){
        login_log a = new login_log();
        a.Read_log();
        String Class = a.login_log[4];
        String Year = jComboBox1.getSelectedItem().toString();
        String Semester = jComboBox2.getSelectedItem().toString();
        
        try{
               File file1 = new File("C:\\DB\\Class\\"+Class+" "+Year+"년도 "+Semester);
               File file = new File("C:\\DB\\Class\\"+Class+" "+Year+"년도 "+Semester+"\\allclass.txt");

               if(!file1.exists()){
                   JOptionPane.showMessageDialog(null, "학기가 개설되지 않았습니다.\n수업담당팀에 문의하세요.");
                   jTable2.setVisible(false);
                   jButton1.setEnabled(false);
                   jButton2.setEnabled(false);
                   jButton5.setEnabled(false);
               }
               else{
                   jTable2.setVisible(true);
                   FileReader filereader = new FileReader(file);
               try (BufferedReader bufReader = new BufferedReader(filereader)) {
                    DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
                    model.setNumRows(0);
                    Object[] tableLines = bufReader.lines().toArray(); 
                    for(int i=0; i< tableLines.length;i++){
                        String line=tableLines[i].toString().trim();
                            String[] dataRow = line.split("\t");
                            model.addRow(dataRow);
                    }
                    filereader.close();
                  bufReader.close();
               }}
            }catch (FileNotFoundException e){
                System.out.println(e);
            }catch(IOException e){
                System.out.println(e);
            }
        }
    
    private void Save_Writelog(){
        login_log a = new login_log();
        a.Read_log();
        String Class = a.login_log[4];
        
        String Year = jComboBox1.getSelectedItem().toString();
        String Semester = jComboBox2.getSelectedItem().toString();
            try{
            File file = new File("C:\\DB\\Class\\"+Class+" "+Year+"년도 "+Semester+"\\allclass.txt");
            if(!file.exists()){
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);
            for(int i = 0; i<jTable2.getRowCount();i++){
                for(int j = 0;j<jTable2.getColumnCount();j++){
                    bw.write(jTable2.getModel().getValueAt(i, j)+"\t");
                }
                bw.write("\n");
            }
            bw.close();
            fw.close(); 
        }catch(IOException ex){
            System.out.println(ex);
        }
        //////////////////////////////////////////학기 로그 작성
        try{
            File file = new File("C:\\DB\\Class\\"+Class+" "+Year+"년도 "+Semester+"\\Semester_log.txt");
            if(!file.exists()){
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(a.login_log[1]+"\t"+a.login_log[2]+"\t"+jLabel12.getText()+"\t"+"-");
                bw.write("\n");
            
            bw.close();
            fw.close(); 
        }catch(IOException ex){
            System.out.println(ex);
        }    
            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_Setclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_Setclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_Setclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_Setclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_Setclass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
