/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graduate.Gstaff_view;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rlarl
 */
public class Gstaff_Newclass extends javax.swing.JFrame {

    /**
     * Creates new form Gstaff_Newclass
     */
    public Gstaff_Newclass() {
        initComponents();
        ReadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClassNum_Field = new javax.swing.JTextField();
        ClassBox_Box = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        ClassInfo_Field = new javax.swing.JTextArea();
        NewClass_Button = new javax.swing.JButton();
        Updata_Button = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();
        Goback_Botton = new javax.swing.JButton();
        ClassName_Field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ClassCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ClassSize_Box = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ClassNum_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ClassNum_FieldFocusLost(evt);
            }
        });

        ClassBox_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "선택 없음", "전산학과", "전자공학과", "화학공학과", "기계공학과", "항공우주공학과" }));
        ClassBox_Box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ClassBox_BoxItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        ClassInfo_Field.setLineWrap(true);
        ClassInfo_Field.setTabSize(0);
        ClassInfo_Field.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ClassInfo_Field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(ClassInfo_Field);

        NewClass_Button.setText("등  록");
        NewClass_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewClass_ButtonActionPerformed(evt);
            }
        });

        Updata_Button.setText("수  정");
        Updata_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Updata_ButtonActionPerformed(evt);
            }
        });

        Delete_Button.setText("삭  제");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });

        Goback_Botton.setText("이  전");
        Goback_Botton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Goback_BottonActionPerformed(evt);
            }
        });

        jLabel1.setText("학 과");

        ClassCode.setEditable(false);

        jLabel3.setText("강좌 번호");

        jLabel4.setText("강좌 이름");

        ClassSize_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "2", "3", "4" }));

        jLabel5.setText("학점");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ClassBox_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ClassCode, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ClassNum_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(ClassSize_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ClassName_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Updata_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Goback_Botton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NewClass_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassNum_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassBox_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewClass_Button)
                    .addComponent(ClassName_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClassSize_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Updata_Button)
                        .addGap(18, 18, 18)
                        .addComponent(Delete_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Goback_Botton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewClass_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewClass_ButtonActionPerformed
        Object[] row = new Object[6];    
            if(ClassBox_Box.getSelectedItem().equals("선택 없음")){
                JOptionPane.showMessageDialog(null, "학과를 선택하세요.");    
            }
            else if(ClassNum_Field.getText().equals("")){
                JOptionPane.showMessageDialog(null, "강좌번호를 입력하세요.");     
            }
            else if(ClassSize_Box.getSelectedItem().equals("---")){
                JOptionPane.showMessageDialog(null, "학점 수를 선택하세요.");
            }
            else if(ClassName_Field.getText().equals("")){
                JOptionPane.showMessageDialog(null, "강좌이름을 입력하세요.");   
            }
            else if(ClassInfo_Field.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "강좌설명을 작성하세요."); 
            }
            else{
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                boolean result = true;
                for(int i=0;i<model.getRowCount();i++){
                   String a = model.getValueAt(i, 2).toString();
                   String b = model.getValueAt(i, 3).toString();
                   if(a.equals(ClassCode.getText()+ClassNum_Field.getText())){
                    JOptionPane.showMessageDialog(null, "이미 존재하는 강좌번호입니다. \n 새로운 번호를 부여하세요.");
                     result = false;
                     break;
                   }
                   else if(a.contains(ClassCode.getText())){
                     if(ClassName_Field.getText().equals(b)){
                         JOptionPane.showMessageDialog(null, "이미 존재하는 강좌입니다.");
                         result = false;
                         break;
                     }
                   }
                    
                
                } 
                
                if(result){
                row[0] = "X";
                row[1] = ClassBox_Box.getSelectedItem();
                row[2] = ClassCode.getText()+ClassNum_Field.getText();
                row[3] = ClassName_Field.getText();
                row[4] = ClassSize_Box.getSelectedItem();
                row[5] = ClassInfo_Field.getText();
            model.addRow(row);
            ClassCode.setText("");
            ClassNum_Field.setText("");
            ClassInfo_Field.setText("");
            ClassBox_Box.setSelectedItem("선택 없음");
            ClassSize_Box.setSelectedItem("---");
            ClassName_Field.setText("");
            SaveFile();
            }
            }
            
    }//GEN-LAST:event_NewClass_ButtonActionPerformed

    private void ClassBox_BoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ClassBox_BoxItemStateChanged
        if(ClassBox_Box.getSelectedItem().equals("선택 없음")){
            ClassCode.setText("");
        }
        else if(ClassBox_Box.getSelectedItem().equals("전산학과")){
            ClassCode.setText("A");
        }
        else if(ClassBox_Box.getSelectedItem().equals("전자공학과")){
            ClassCode.setText("B");
        }
        else if(ClassBox_Box.getSelectedItem().equals("화학공학과")){
            ClassCode.setText("C");
        }
        else if(ClassBox_Box.getSelectedItem().equals("기계공학과")){
            ClassCode.setText("D");
        }
        else{
            ClassCode.setText("E");
        }
    }//GEN-LAST:event_ClassBox_BoxItemStateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();
        ClassName_Field.setText(model.getValueAt(i, 3).toString());
        ClassInfo_Field.setText(model.getValueAt(i, 5).toString());
        ClassSize_Box.setSelectedItem(model.getValueAt(i, 4));
        ClassBox_Box.setSelectedItem(model.getValueAt(i, 1));
        
        String m = model.getValueAt(i, 2).toString();
        String n = m.substring(1);
        ClassNum_Field.setText(n);
    }//GEN-LAST:event_jTable1MouseClicked

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();
        if(jTable1.getValueAt(i, 0).equals("O")){
            JOptionPane.showMessageDialog(null, "삭제가 불가능한 데이터입니다.");
            ClassCode.setText("");
            ClassNum_Field.setText("");
            ClassInfo_Field.setText("");
            ClassBox_Box.setSelectedItem("선택 없음");
            ClassSize_Box.setSelectedItem("---");
            ClassName_Field.setText("");
        }
        
        else if(i >=0 ){
            model.removeRow(i);
            ClassCode.setText("");
            ClassNum_Field.setText("");
            ClassInfo_Field.setText("");
            ClassBox_Box.setSelectedItem("선택 없음");
            ClassSize_Box.setSelectedItem("---");
            ClassName_Field.setText("");
            SaveFile();
        }
        else{
            JOptionPane.showMessageDialog(null, "삭제할 데이터가 없습니다.");
        }
        
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    private void Updata_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Updata_ButtonActionPerformed
        int i = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        if(jTable1.getValueAt(i, 0).equals("O")){
            JOptionPane.showMessageDialog(null, "수정이 불가능한 데이터입니다.");
            ClassCode.setText("");
            ClassNum_Field.setText("");
            ClassInfo_Field.setText("");
            ClassBox_Box.setSelectedItem("선택 없음");
            ClassSize_Box.setSelectedItem("---");
            ClassName_Field.setText("");
        }
        else if(i>=0){
            model.setValueAt(ClassBox_Box.getSelectedItem(),i,1);
            model.setValueAt(ClassCode.getText()+ClassNum_Field.getText(), i, 2);
            model.setValueAt(ClassName_Field.getText(), i, 3);
            model.setValueAt(ClassInfo_Field.getText(), i, 5);
            model.setValueAt(ClassSize_Box.getSelectedItem(), i, 4);
            ClassCode.setText("");
            ClassNum_Field.setText("");
            ClassInfo_Field.setText("");
            ClassBox_Box.setSelectedItem("선택 없음");
            ClassSize_Box.setSelectedItem("---");
            ClassName_Field.setText("");
            SaveFile();
        }
        else{
            JOptionPane.showMessageDialog(null, "수정하실 행을 선택하세요.");
        }
    }//GEN-LAST:event_Updata_ButtonActionPerformed

    private void ClassNum_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ClassNum_FieldFocusLost
        boolean Number = false;
            boolean Alpha = false;
            boolean Korean = false;
            for(int i=0; i<ClassNum_Field.getText().length();i++){
            int index = ClassNum_Field.getText().charAt(i);
            
            if(index>=65 && index<=122){
                Alpha = true;  
            }
            else if(index<=57 && index >= 48){
                Number = true;
            }
            else{
                Korean = true;
            }
           }
            if(Alpha==true || Korean == true){
                JOptionPane.showMessageDialog(null, "숫자만 입력하세요.");
            }
            
            if(ClassNum_Field.getText().length()!=3){
                JOptionPane.showMessageDialog(null, "강좌번호는 3자리로 입력해주세요.\n(ex : A001)");
            }
    }//GEN-LAST:event_ClassNum_FieldFocusLost

    private void Goback_BottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Goback_BottonActionPerformed
        Gstaff_firstview g = new Gstaff_firstview();
        g.setVisible(true);
        dispose();
    }//GEN-LAST:event_Goback_BottonActionPerformed
  
    private void ReadTable(){
        try{
               File file = new File("C:\\DB\\Class\\AllClass.txt");
               FileReader filereader = new FileReader(file);
               try (BufferedReader bufReader = new BufferedReader(filereader)) {
                    String firstline = bufReader.readLine().trim();
                    String[] columsName = firstline.split("\t");
                    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                    model.setNumRows(0);
                    model.setColumnIdentifiers(columsName);  
                    Object[] tableLines = bufReader.lines().toArray(); 
                    for(int i=0; i< tableLines.length;i++){
                        String line=tableLines[i].toString().trim();
                        String[] dataRow = line.split("\t");
                        model.addRow(dataRow);
                    }
                    
                    filereader.close();
                  bufReader.close();
                }
            }catch (FileNotFoundException e){
                System.out.println(e);
            }catch(IOException e){
                System.out.println(e);
            }
         jTable1.getColumnModel().getColumn(0).setMaxWidth(20);
    }
    
    public void SaveFile(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            try{
            File file = new File("C:\\DB\\Class\\AllClass.txt");
            if(!file.exists()){
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            BufferedWriter bw = new BufferedWriter(fw);
            String ob;
            for(int m=0;m<jTable1.getColumnCount();m++)
            { 
               ob = model.getColumnName(m);
               bw.write(ob+"\t");  
            }
            bw.write("\n");
            for(int i = 0; i<jTable1.getRowCount();i++){
                for(int j = 0;j<jTable1.getColumnCount();j++){
                    bw.write(jTable1.getModel().getValueAt(i, j)+"\t");
                }
                bw.write("\n");
            }
            bw.close();
            fw.close(); 
            ClassCode.setText("");
            ClassNum_Field.setText("");
            ClassInfo_Field.setText("");
            ClassBox_Box.setSelectedItem("선택 없음");
            ClassSize_Box.setSelectedItem("---");
            ClassName_Field.setText("");
        }catch(IOException ex){
            System.out.println(ex);
        }
    }
    

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gstaff_Newclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gstaff_Newclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gstaff_Newclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gstaff_Newclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gstaff_Newclass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ClassBox_Box;
    private javax.swing.JTextField ClassCode;
    private javax.swing.JTextArea ClassInfo_Field;
    private javax.swing.JTextField ClassName_Field;
    private javax.swing.JTextField ClassNum_Field;
    private javax.swing.JComboBox<String> ClassSize_Box;
    private javax.swing.JButton Delete_Button;
    private javax.swing.JButton Goback_Botton;
    private javax.swing.JButton NewClass_Button;
    private javax.swing.JButton Updata_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
