/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graduate.login;

import graduate.Gstaff_view.Gstaff_firstview;
import graduate.Hstaff_view.Hstaff_firstview;
import graduate.professor_view.professor_firstview;
import graduate.student_view.student_firstview;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author rlarl
 */
public class change_PW extends javax.swing.JFrame {

    /**
     * Creates new form change_PW
     */
    public change_PW() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Origin_PW = new javax.swing.JPasswordField();
        New_PW = new javax.swing.JPasswordField();
        New_PW2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        warning1 = new javax.swing.JLabel();
        warning2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("이  전");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("변  경");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jLabel1.setText("패스워드 변경");

        Origin_PW.setColumns(7);
        Origin_PW.setToolTipText("");
        Origin_PW.setActionCommand("<Not Set>");
        Origin_PW.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Origin_PWCaretUpdate(evt);
            }
        });

        New_PW.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                New_PWCaretUpdate(evt);
            }
        });

        New_PW2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                New_PW2CaretUpdate(evt);
            }
        });

        jLabel2.setText("기존 패스워드");

        jLabel3.setText("새 패스워드");

        jLabel4.setText("새 패스워드 확인");

        jLabel5.setFont(new java.awt.Font("굴림", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("* 패스워드는 영문자 및 숫자 포함 7자리여야 합니다.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(New_PW, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Origin_PW, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(New_PW2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(warning1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(warning2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(28, 28, 28)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Origin_PW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(warning))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(New_PW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(warning1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(New_PW2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(warning2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Origin_PWCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Origin_PWCaretUpdate

        login_log a = new login_log();
        a.Read_log();
        String pw = a.login_log[0];
        if(Origin_PW.getText().equals("")){
            warning.setText("비어있음.");
        }
        else if(Origin_PW.getText().equals(pw)){
            warning.setText("O");
        }
        else{
            warning.setText("일치하지 않습니다.");
        }
    }//GEN-LAST:event_Origin_PWCaretUpdate

    private void New_PWCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_New_PWCaretUpdate
        if(New_PW.getText().equals("")){
            warning1.setText("비어있음.");
        }
        else if(New_PW.getText().length()>7){
            warning1.setText("너무 깁니다.");
        } 
        else if(New_PW.getText().length()<7){
            warning1.setText("너무 짧습니다.");
        }
        else if(New_PW.getText().equals(Origin_PW.getText())){
            warning1.setText("기존 패스워드와 동일합니다.");
        }
        else{
            boolean Number = false;
            boolean Alpha = false;
            for(int i=0; i<New_PW.getText().length();i++){
            int index = New_PW.getText().charAt(i);
            
            if(index>=65 && index<=122){
                Alpha = true;  
            }
            else if(index<=57 && index >= 48){
                Number = true;
            }
           }
            if(Number==false){
                warning1.setText("숫자를 포함해 주세요.");
            }
            else if(Alpha==false){
                warning1.setText("영문자를 포함해 주세요");
            }
            else{
                warning1.setText("O");
            }
        }
    }//GEN-LAST:event_New_PWCaretUpdate

    private void New_PW2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_New_PW2CaretUpdate
        if(New_PW2.getText().equals("")){
            warning2.setText("비어있음.");
        }
        else if(!New_PW2.getText().equals(New_PW.getText())){
            warning2.setText("일치하지 않습니다.");
        } else if(New_PW2.getText().equals(New_PW.getText())){
            warning2.setText("O");
        }
    }//GEN-LAST:event_New_PW2CaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        student_firstview s = new student_firstview();
        professor_firstview p = new professor_firstview();
        Hstaff_firstview h = new Hstaff_firstview();
        Gstaff_firstview g = new Gstaff_firstview();
        login_log a = new login_log();
        a.Read_log();
        if(a.login_log[1].contains("S")){
            s.setVisible(true);
            dispose();
        }
        else if(a.login_log[1].contains("P")){
            p.setVisible(true);
            dispose();
        }
        else if(a.login_log[1].contains("H")){
            h.setVisible(true);
            dispose();
        }
        else{
            g.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(warning.getText().equals("O") && warning1.getText().equals("O") && warning2.getText().equals("O")){
            login_log a = new login_log();
            a.Read_log();
            a.login_log[0] = New_PW.getText();
            if(a.login_log[1].contains("S")){
                    File file = new File("C:\\DB\\login_data\\student_table.txt");		
		String dummy = "";
		try {
			BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(file)));
                        String line;
                        while(true){
                        line = br.readLine(); //읽으며 이동
			
                        if(line.contains(a.login_log[1])){
                            break;
                        }
                        dummy += (line + "\r\n" );
                        }
                        
                        for(int j =0; j<a.login_log.length;j++){
                            dummy += (a.login_log[j]+"\t");
                        }
                        dummy += "\n";
                        while((line = br.readLine())!=null) {
				dummy += (line + "\r\n" ); 
			}
                        FileWriter fw = new FileWriter("C:\\DB\\login_data\\student_table.txt");

			fw.write(dummy);			
			fw.close();

			br.close();
		} catch (Exception e) {
			e.printStackTrace();

		}
                JOptionPane.showMessageDialog(null, "비밀번호가 변경되었습니다.\n다시 로그인 해주세요.");
                login_frame s = new login_frame();
                s.setVisible(true);
                dispose();
            }
            else if(a.login_log[1].contains("P")){
                File file = new File("C:\\DB\\login_data\\professor_table.txt");		
		String dummy = "";
		try {
			BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(file)));
                        String line;
                        while(true){
                        line = br.readLine(); //읽으며 이동
			
                        if(line.contains(a.login_log[1])){
                            break;
                        }
                        dummy += (line + "\r\n" );
                        }
                        
                        for(int j =0; j<a.login_log.length;j++){
                            dummy += (a.login_log[j]+"\t");
                        }
                        dummy += "\n";
                        while((line = br.readLine())!=null) {
				dummy += (line + "\r\n" ); 
			}
                        FileWriter fw = new FileWriter("C:\\DB\\login_data\\professor_table.txt");

			fw.write(dummy);			
			fw.close();

			br.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
                JOptionPane.showMessageDialog(null, "비밀번호가 변경되었습니다.\n다시 로그인 해주세요.");
                login_frame s = new login_frame();
                s.setVisible(true);
                dispose();
            }
            else{
                File file = new File("C:\\DB\\login_data\\staff_table.txt");		
		String dummy = "";
		try {
			BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(file)));
                        String line;
                        while(true){
                        line = br.readLine(); //읽으며 이동
			
                        if(line.contains(a.login_log[1])){
                            break;
                        }
                        dummy += (line + "\r\n" );
                        }
                        
                        for(int j =0; j<a.login_log.length;j++){
                            dummy += (a.login_log[j]+"\t");
                        }
                        dummy += "\n";
                        while((line = br.readLine())!=null) {
				dummy += (line + "\r\n" ); 
			}
                        FileWriter fw = new FileWriter("C:\\DB\\login_data\\staff_table.txt");

			fw.write(dummy);			
			fw.close();

			br.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
                JOptionPane.showMessageDialog(null, "비밀번호가 변경되었습니다.\n다시 로그인 해주세요.");
                login_frame s = new login_frame();
                s.setVisible(true);
                dispose();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "다시 한번 확인하세요.");
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(change_PW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(change_PW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(change_PW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(change_PW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new change_PW().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField New_PW;
    private javax.swing.JPasswordField New_PW2;
    private javax.swing.JPasswordField Origin_PW;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel warning;
    private javax.swing.JLabel warning1;
    private javax.swing.JLabel warning2;
    // End of variables declaration//GEN-END:variables
}
